name: CI Kronicle Metadata

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:

  ci-kronicle-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Set up JDK 11 🏗
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Validate Gradle wrapper 👀
        uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b

      - name: Validate kronicle.yaml 👀
        run: ./gradlew validateKronicleMetadata
